### ISSUE TITLE
Fatal error: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by jefferson-william** [snadrus/grunt-rev-all#2]
Hello,

Turning the grunt-rev-all task, I came across the following error: *\* Fatal error: Can not read property 'length' of null **.

As I'm not sure what to say about this error, I created a test repository to play such a problem [here](https://github.com/jefferson-william/grunt-rev-all-example).

I made the following modifications - even without understanding - in the file **grunt-rev-all.js** of package, in line 90, in order to avoid the "Fatal error":

```
if (!linksFound[lenToEnd] || !refPath.match(/\//g)) continue;
```

I'm available.

Thank you!

**Comment by snadrus** [comment]
It looks like you don't have a runtimeBase entry specified. That's where
you say what the rootpath equivalent will go. Without that config, the
purpose of the tool is moot, hence the crash.

On Sat, Jan 9, 2016 at 10:18 AM, jefferson-william <notifications@github.com
