### ISSUE TITLE
completedSet is not an array

### ISSUE THREAD

**Issue by robstove** [snadrus/grunt-rev-all#4]
At line:
https://github.com/snadrus/grunt-rev-all/blob/master/tasks/grunt-rev-all.js#L146

You are checking `completedSet.length == ctAllFiles` however completedSet is an object graph not an array so length is always undefined. This prevents the done() call which prevents tasks defined after grunt-rev-all from executing.

**Comment by snadrus** [comment]
Great catch! Would you like to submit a patch or would you like for me to fix it?
